### ISSUE TITLE
Bug Report: Unable to upload .wav files

### ISSUE THREAD

**Issue by martin-international** [audiodude/rainfall#21]
**System info:**
**_OS:_** Windows 10
**_Browsers:_** Firefox and Chrome

**Description:** I am unable to upload .wav files as a release. I first attempted on Firefox with extensions on, then with extensions off, and finally I attempted on Chrome with extensions off. I tried multiple .wav files that are accepted on other platforms.

**Error Message:** An unknown error has occurred

**Debug Info:** No errors or debug info are printed in the developer tools browser panels

**Steps to reproduce:**
1. Login
2. Create a new project and configure it, or configure an existing project
3. Click to add release
4. Select a .wav file for the release upload
5. Select upload
6. Wait briefly until the error message is displayed

**Comment by audiodude** [comment]
I don't really have any WAV files, but I just converted an MP3 to WAV to test and it worked fine. By any chance could you DM me the file on Mastodon or email it to audiodude@gmail.com?

Thanks!

**Comment by audiodude** [comment]
Or maybe you could just try again? I just set up persistent logging for production.

**Comment by martin-international** [comment]
I've tried again, issue reproduced.

Additional details:

- I am using 24-bit WAV files
- As such, they are large (>100MB)

I imagine the file size could be directly provoking the error.

I've sent you this info and the track links via email.

**Comment by audiodude** [comment]
> * I am using 24-bit WAV files
> * As such, they are large (>100MB)

This is the problem. I set a 100MB max upload size, just for sanity. I assumed most MP3s are 3-8 MB and most WAVs are 30-50.

I guess the options are to increase that, which doesn't sound great (I won't be able to serve many users) or to be more transparent about the failure mode.

Also, I could make it more clear that Faircamp is going to transcode all of your tracks to opus (presumably so they can be played on linux?) anyways, so the original fidelity doesn't matter
