### ISSUE TITLE
Bug Report: Link to open preview site in new window results in 404 error

### ISSUE THREAD

**Issue by martin-international** [audiodude/rainfall#22]
**System info:**
**_OS:_** Windows 10
**_Browsers:_** Firefox and Chrome

**Description:** When I click the preview site button, and then proceed to click on the link to open the preview in a new site, the page that opens returns a 404 Not Found error. Reproduced on FF and Chrome, with relevant extensions off on both browsers.

**Error Message:** 404 / Not Found

**Debug Info:** No errors or debug info are printed in the developer tools browser panels

**Steps to reproduce:**
1. Login
2. Create and edit a new project, or edit an existing project
3. Add at least one release
4. Select Preview Site
5. Click on the link to open the preview in a new window
6. Observe 404 error

**Comment by audiodude** [comment]
This is likely because there was a problem generating the preview. I did notice in testing that sometimes Faircamp will fail, and print a message, but still exit with status=0.

**Comment by martin-international** [comment]
Going through again and uploading the same release file just now, a preview was successfully generated (and deployed). Feel free to reopen if this needs further debugging.
