### ISSUE TITLE
Bug Report: Deploy button unavailable

### ISSUE THREAD

**Issue by martin-international** [audiodude/rainfall#23]
**System info:**
**_OS:_** Windows 10
**_Browsers:_** Firefox and Chrome

**Description:** After clicking the preview button, the deploy button remains unselectable.

**Error Message:** N/A

**Debug Info:** No errors or debug info are printed in the developer tools browser panels

**Steps to reproduce:**
1. Login
2. Create and edit a new project, or edit an existing project
3. Add at least one release
4. Select Preview Site
5. Optional: Click on the link to open the preview in a new window and observe 404 error
6. (On Rainfall:) Observe that the Deploy button is still "greyed" out
7. Click on Deploy button and observe that no action occurs

**Comment by audiodude** [comment]
This is the correct behavior. Since your site failed to properly generate a preview, the deploy is (correctly) not available.
